---
title: "Drug Pertubations - DESeq2 Analysis - HCC1806"
author: "Matthew Berginski"
date: "2/17/2020"
output: html_document
---

```{r setup, include=FALSE}
library("tximeta")
library("DESeq2")

library("AnnotationDbi")
library("org.Hs.eg.db")
library("BiocParallel")

register(MulticoreParam(8))

library(biomaRt)

library(DarkKinaseTools)
library(here)
library(tidyverse)
library(glue)
library(patchwork)

library(BerginskiRMisc)
library(ggupset)
library(tictoc)
```

```{r}
if (! file.exists(here('gene_to_hgnc.csv'))) {
	ensembl = biomaRt::useMart("ensembl",dataset="hsapiens_gene_ensembl")
	gene_to_hgnc = biomaRt::getBM(attributes = c('ensembl_gene_id','hgnc_symbol'), mart = ensembl)
	write_csv(gene_to_hgnc, here('gene_to_hgnc.csv'))
} else {
	gene_to_hgnc = readr::read_csv(here('gene_to_hgnc.csv'))
}

source(here('shared_functions.R'))
```

```{r}
exp_info = tribble(
	~files, ~batch, ~rep, ~treatment,
	
	here('salmon_alignments/HCC1806/batch_01/rep_01/DMSO/quant.sf'), 1, 1, "DMSO",
	here('salmon_alignments/HCC1806/batch_01/rep_02/DMSO/quant.sf'), 1, 2, "DMSO",
	here('salmon_alignments/HCC1806/batch_01/rep_01/Bort/quant.sf'), 1, 1, "Bort",
	here('salmon_alignments/HCC1806/batch_01/rep_02/Bort/quant.sf'), 1, 2, "Bort",
	here('salmon_alignments/HCC1806/batch_01/rep_01/Ent/quant.sf'), 1, 1, "Ent",
	here('salmon_alignments/HCC1806/batch_01/rep_02/Ent/quant.sf'), 1, 2, "Ent",
	here('salmon_alignments/HCC1806/batch_01/rep_01/MK2206/quant.sf'), 1, 1, "MK2206",
	here('salmon_alignments/HCC1806/batch_01/rep_02/MK2206/quant.sf'), 1, 2, "MK2206",
	here('salmon_alignments/HCC1806/batch_01/rep_01/Navit/quant.sf'), 1, 1, "Navitoclax",
	here('salmon_alignments/HCC1806/batch_01/rep_02/Navit/quant.sf'), 1, 2, "Navitoclax",
	here('salmon_alignments/HCC1806/batch_01/rep_01/Tram/quant.sf'), 1, 1, "Trametinib",
	here('salmon_alignments/HCC1806/batch_01/rep_02/Tram/quant.sf'), 1, 2, "Trametinib",

	here('salmon_alignments/HCC1806/batch_02/rep_01/DMSO/quant.sf'), 2, 1, "DMSO",
	here('salmon_alignments/HCC1806/batch_02/rep_02/DMSO/quant.sf'), 2, 2, "DMSO",
	here('salmon_alignments/HCC1806/batch_02/rep_01/CoCl2/quant.sf'), 2, 1, "CoCl2",
	here('salmon_alignments/HCC1806/batch_02/rep_02/CoCl2/quant.sf'), 2, 2, "CoCl2",
	here('salmon_alignments/HCC1806/batch_02/rep_01/Palbo/quant.sf'), 2, 1, "Palbo",
	here('salmon_alignments/HCC1806/batch_02/rep_02/Palbo/quant.sf'), 2, 2, "Palbo",
	here('salmon_alignments/HCC1806/batch_02/rep_01/SGC/quant.sf'), 2, 1, "SGCCP30",
	here('salmon_alignments/HCC1806/batch_02/rep_01/SGC/quant.sf'), 2, 2, "SGCCP30",
	here('salmon_alignments/HCC1806/batch_02/rep_01/Tram_100/quant.sf'), 2, 1, "Tram_100",
	here('salmon_alignments/HCC1806/batch_02/rep_02/Tram_100/quant.sf'), 2, 2, "Tram_100",
	here('salmon_alignments/HCC1806/batch_02/rep_01/Tram_500/quant.sf'), 2, 1, "Tram_500",
	here('salmon_alignments/HCC1806/batch_02/rep_02/Tram_500/quant.sf'), 2, 2, "Tram_500",

	here('salmon_alignments/HCC1806/batch_03/rep_01/DMSO/quant.sf'), 3, 1, "DMSO",
	here('salmon_alignments/HCC1806/batch_03/rep_02/DMSO/quant.sf'), 3, 2, "DMSO",
	here('salmon_alignments/HCC1806/batch_03/rep_01/Alisertib/quant.sf'), 3, 1, "Alisertib",
	here('salmon_alignments/HCC1806/batch_03/rep_02/Alisertib/quant.sf'), 3, 2, "Alisertib",
	here('salmon_alignments/HCC1806/batch_03/rep_01/Dinaciclib/quant.sf'), 3, 1, "Dinaciclib",
	here('salmon_alignments/HCC1806/batch_03/rep_02/Dinaciclib/quant.sf'), 3, 2, "Dinaciclib",
	here('salmon_alignments/HCC1806/batch_03/rep_01/JIB04/quant.sf'), 3, 1, "JIB.04",
	here('salmon_alignments/HCC1806/batch_03/rep_02/JIB04/quant.sf'), 3, 2, "JIB.04",
	here('salmon_alignments/HCC1806/batch_03/rep_01/Paclitaxel/quant.sf'), 3, 1, "Paclitaxel",
	here('salmon_alignments/HCC1806/batch_03/rep_02/Paclitaxel/quant.sf'), 3, 2, "Paclitaxel",
	here('salmon_alignments/HCC1806/batch_03/rep_01/Ruxolitinib/quant.sf'), 3, 1, "Ruxolitinib",
	here('salmon_alignments/HCC1806/batch_03/rep_02/Ruxolitinib/quant.sf'), 3, 2, "Ruxolitinib",
	
	#These are Runs from John Zawistowski's paper
	here('salmon_alignments/Zawistowski_HCC1806/batch_01/rep_01/DMSO/quant.sf'), 4, 1, "DMSO",
	here('salmon_alignments/Zawistowski_HCC1806/batch_01/rep_01/Tramet/quant.sf'), 4, 1, "Trametinib John",
	here('salmon_alignments/Zawistowski_HCC1806/batch_01/rep_02/DMSO/quant.sf'), 4, 2, "DMSO",
	here('salmon_alignments/Zawistowski_HCC1806/batch_01/rep_02/Tramet/quant.sf'), 4, 2, "Trametinib John"

)
```

```{r}
tic()
drug_perturb_files = exp_info %>%
	mutate(names = paste0(treatment,"_",batch,"_",rep)) %>%
	#ensure that DMSO is the first level, forcing the fold change values to be
	#calculated as drug_treatment/DMSO
	mutate(treatment = relevel(as.factor(treatment), "DMSO"),
				 batch = as.factor(batch),
				 rep = as.factor(rep)) %>%
	identity()

drug_perturb_files$batch = as.factor(drug_perturb_files$batch)
drug_perturb_files$rep = as.factor(drug_perturb_files$rep)

drug_perturb_exp = summarizeToGene(tximeta(drug_perturb_files))
dds <- DESeqDataSet(drug_perturb_exp, design = ~batch + treatment)

#Code to deal with collapsing technical replicates into single columns in
#DESeq, will only be used if a "run" column is defined, which should be a
#unique name for each run, which collapses together in the names field.
if ("run" %in% colnames(drug_perturb_files)) {
	dds <- collapseReplicates(dds, dds$names, dds$run)
}
keep <- rowSums(counts(dds)) > 1
dds <- dds[keep,]

dds_analysis <- DESeq(dds)

full_DESeq = tribble(~hgnc_symbol,~ensembl_gene_id, ~baseMean, ~log2FoldChange, ~lfcSE, ~stat, ~pvalue, ~padj, ~treatment)
summary_stats = tribble(~treatment,~number_2fold,~num_kinases,~num_dark_kinases,~dk_diff_str)

for (this_comparison in resultsNames(dds_analysis)[-1]) {
	dds_results = lfcShrink(dds_analysis, coef=this_comparison, type="apeglm")

	full_DESeq = rbind(
		full_DESeq,
		dds_results %>%
			as.data.frame() %>%
			rownames_to_column(var = "ensembl_gene_id") %>%
			mutate(treatment = this_comparison) %>%
			left_join(gene_to_hgnc) %>%
			dplyr::select("hgnc_symbol","treatment",everything())
	)

	dds_results_filtered = dds_results %>%
		as.data.frame() %>%
		rownames_to_column(var = "ensembl_gene_id") %>%
		filter(abs(log2FoldChange) >= 1, padj <= 0.05) %>%
		left_join(gene_to_hgnc) %>%
		filter(!is.na(hgnc_symbol)) %>%
		mutate("treatment" = this_comparison)

	dds_results_filtered_kinase = dds_results_filtered %>%
		filter(hgnc_symbol %in% all_kinases$symbol)

	dds_results_filtered_dark_kinase = dds_results_filtered %>%
		filter(hgnc_symbol %in% dark_kinases$symbol)

	summary_stats = rbind(
		summary_stats,
		data.frame(
			treatment = this_comparison,
			number_2fold = dim(dds_results_filtered)[1],
			num_kinases = dim(dds_results_filtered_kinase)[1],
			num_dark_kinases = dim(dds_results_filtered_dark_kinase)[1],
			dk_diff_str = ifelse(dim(dds_results_filtered_dark_kinase)[1] == 0,
													 "",
													 glue_collapse(sort(dds_results_filtered_dark_kinase$hgnc_symbol), sep=" | "))
		)
	)
}

write_csv(full_DESeq,here('DESeq_results/HCC1806_only_DESeq2_results.csv.gz'))
write_csv(summary_stats,here('DESeq_results/HCC1806_only_DESeq2_summary.csv'))

toc()
```


# PCA Plots

```{r}
vsd <- vst(dds, blind=FALSE)

plotPCA(vsd, intgroup=c("treatment","batch"))

```