---
title: "Drug Pertubations - DESeq2 Analysis - SUM159"
author: "Matthew Berginski"
date: "2/17/2020"
output: html_document
---

```{r setup, include=FALSE}
library("tximeta")
library("DESeq2")

library("AnnotationDbi")
library("org.Hs.eg.db")
library("BiocParallel")

register(MulticoreParam(4))

library(biomaRt)

library(DarkKinaseTools)
library(here)
library(tidyverse)
library(glue)
library(patchwork)

library(BerginskiRMisc)
library(ggupset)


```

```{r}
if (! file.exists(here('gene_to_hgnc.csv'))) {
	ensembl = biomaRt::useMart("ensembl",dataset="hsapiens_gene_ensembl")
	gene_to_hgnc = biomaRt::getBM(attributes = c('ensembl_gene_id','hgnc_symbol'), mart = ensembl)
	write_csv(gene_to_hgnc, here('gene_to_hgnc.csv'))
} else {
	gene_to_hgnc = readr::read_csv(here('gene_to_hgnc.csv'))
}
```

```{r}
full_DESeq = tribble(~baseMean, ~log2FoldChange, ~lfcSE, ~stat, ~pvalue, ~padj, ~treatment, ~batch)
summary_stats = tribble(~treatment,~batch,~number_2fold,~num_kinases,~num_dark_kinases,~dk_diff_str)

#get the function used to run DESeq2 and return results
source(here('shared_functions.R'))
```

# Batch 1

## Dinaciclib

```{r Dinac run}
exp_info = tribble(
	~files, ~batch, ~rep, ~treatment,
	
	here('salmon_alignments/batch_01/rep_01/DMSO/quant.sf'), 1, 1, "DMSO",
	here('salmon_alignments/batch_01/rep_01/Dinac/quant.sf'), 1, 1, "Dina",
	here('salmon_alignments/batch_01/rep_02/DMSO/quant.sf'), 1, 2, "DMSO",
	here('salmon_alignments/batch_01/rep_02/Dinac/quant.sf'), 1, 2, "Dina"
)

temp = collect_all_DESeq(exp_info)
temp$DESeq_full_results = temp$DESeq_full_results %>%
	mutate(treatment = "Dinaciclib", batch = 1)
full_DESeq = rbind(full_DESeq, temp$DESeq_full_results)

temp$DESeq_summary = temp$DESeq_summary %>% 
	mutate(treatment = "Dinaciclib", batch = 1)
summary_stats = rbind(summary_stats, temp$DESeq_summary)
```

## Entinostat

```{r}
exp_info = tribble(
	~files, ~batch, ~rep, ~treatment,
	
	here('salmon_alignments/batch_01/rep_01/DMSO/quant.sf'), 1, 1, "DMSO",
	here('salmon_alignments/batch_01/rep_01/Ent/quant.sf'), 1, 1, "Ent",
	here('salmon_alignments/batch_01/rep_02/DMSO/quant.sf'), 1, 2, "DMSO",
	here('salmon_alignments/batch_01/rep_02/Ent/quant.sf'), 1, 2, "Ent"
)

temp = collect_all_DESeq(exp_info)
temp$DESeq_full_results = temp$DESeq_full_results %>%
	mutate(treatment = "Entinostat", batch = 1)
full_DESeq = rbind(full_DESeq, temp$DESeq_full_results)

temp$DESeq_summary = temp$DESeq_summary %>% 
	mutate(treatment = "Entinostat", batch = 1)
summary_stats = rbind(summary_stats, temp$DESeq_summary)
```

## JIB-04 Low Dose

```{r}
exp_info = tribble(
	~files, ~batch, ~rep, ~treatment,
	
	here('salmon_alignments/batch_01/rep_01/DMSO/quant.sf'), 1, 1, "DMSO",
	here('salmon_alignments/batch_01/rep_01/JIB04/quant.sf'), 1, 1, "JIB-04",
	here('salmon_alignments/batch_01/rep_02/DMSO/quant.sf'), 1, 2, "DMSO",
	here('salmon_alignments/batch_01/rep_02/JIB04/quant.sf'), 1, 2, "JIB-04"
)

temp = collect_all_DESeq(exp_info)
temp$DESeq_full_results = temp$DESeq_full_results %>%
	mutate(treatment = "JIB-04 Low Dose", batch = 1)
full_DESeq = rbind(full_DESeq, temp$DESeq_full_results)

temp$DESeq_summary = temp$DESeq_summary %>% 
	mutate(treatment = "JIB-04 Low Dose", batch = 1)
summary_stats = rbind(summary_stats, temp$DESeq_summary)
```

## MK2206

```{r}
exp_info = tribble(
	~files, ~batch, ~rep, ~treatment,
	
	here('salmon_alignments/batch_01/rep_01/DMSO/quant.sf'), 1, 1, "DMSO",
	here('salmon_alignments/batch_01/rep_01/MK2206/quant.sf'), 1, 1, "MK2206",
	here('salmon_alignments/batch_01/rep_02/DMSO/quant.sf'), 1, 2, "DMSO",
	here('salmon_alignments/batch_01/rep_02/MK2206/quant.sf'), 1, 2, "MK2206"
)

temp = collect_all_DESeq(exp_info)
temp$DESeq_full_results = temp$DESeq_full_results %>%
	mutate(treatment = "MK2206", batch = 1)
full_DESeq = rbind(full_DESeq, temp$DESeq_full_results)

temp$DESeq_summary = temp$DESeq_summary %>% 
	mutate(treatment = "MK2206", batch = 1)
summary_stats = rbind(summary_stats, temp$DESeq_summary)
```

## Trametinib

```{r}
exp_info = tribble(
	~files, ~batch, ~rep, ~treatment,
	
	here('salmon_alignments/batch_01/rep_01/DMSO/quant.sf'), 1, 1, "DMSO",
	here('salmon_alignments/batch_01/rep_01/Tram/quant.sf'), 1, 1, "Tram",
	here('salmon_alignments/batch_01/rep_02/DMSO/quant.sf'), 1, 2, "DMSO",
	here('salmon_alignments/batch_01/rep_02/Tram/quant.sf'), 1, 2, "Tram"
)

temp = collect_all_DESeq(exp_info)
temp$DESeq_full_results = temp$DESeq_full_results %>%
	mutate(treatment = "Trametinib", batch = 1)
full_DESeq = rbind(full_DESeq, temp$DESeq_full_results)

temp$DESeq_summary = temp$DESeq_summary %>% 
	mutate(treatment = "Trametinib", batch = 1)
summary_stats = rbind(summary_stats, temp$DESeq_summary)
```

# Batch 2

## JIB-04 (high dose)

```{r}
exp_info = tribble(
	~files, ~batch, ~rep, ~treatment,
	
	here('salmon_alignments/batch_02/rep_01/DMSO/quant.sf'), 2, 1, "DMSO",
	here('salmon_alignments/batch_02/rep_01/JIB04/quant.sf'), 2, 1, "JIB-04",
	here('salmon_alignments/batch_02/rep_02/DMSO/quant.sf'), 2, 2, "DMSO",
	here('salmon_alignments/batch_02/rep_02/JIB04/quant.sf'), 2, 2, "JIB-04"
)

temp = collect_all_DESeq(exp_info)
temp$DESeq_full_results = temp$DESeq_full_results %>%
	mutate(treatment = "JIB-04 High Dose", batch = 2)
full_DESeq = rbind(full_DESeq, temp$DESeq_full_results)

temp$DESeq_summary = temp$DESeq_summary %>% 
	mutate(treatment = "JIB-04 High Dose", batch = 2)
summary_stats = rbind(summary_stats, temp$DESeq_summary)
```

## Navitoclax

```{r}
exp_info = tribble(
	~files, ~batch, ~rep, ~treatment,
	
	here('salmon_alignments/batch_02/rep_01/DMSO/quant.sf'), 2, 1, "DMSO",
	here('salmon_alignments/batch_02/rep_01/Navi/quant.sf'), 2, 1, "Navi",
	here('salmon_alignments/batch_02/rep_02/DMSO/quant.sf'), 2, 2, "DMSO",
	here('salmon_alignments/batch_02/rep_02/Navi/quant.sf'), 2, 2, "Navi"
)

temp = collect_all_DESeq(exp_info)
temp$DESeq_full_results = temp$DESeq_full_results %>%
	mutate(treatment = "Navitoclax", batch = 2)
full_DESeq = rbind(full_DESeq, temp$DESeq_full_results)

temp$DESeq_summary = temp$DESeq_summary %>% 
	mutate(treatment = "Navitoclax", batch = 2)
summary_stats = rbind(summary_stats, temp$DESeq_summary)
```

## Paclitaxel

```{r}
exp_info = tribble(
	~files, ~batch, ~rep, ~treatment,
	
	here('salmon_alignments/batch_02/rep_01/DMSO/quant.sf'), 2, 1, "DMSO",
	here('salmon_alignments/batch_02/rep_01/Paclit/quant.sf'), 2, 1, "Paclit",
	here('salmon_alignments/batch_02/rep_02/DMSO/quant.sf'), 2, 2, "DMSO",
	here('salmon_alignments/batch_02/rep_02/Paclit/quant.sf'), 2, 2, "Paclit"
)

temp = collect_all_DESeq(exp_info)
temp$DESeq_full_results = temp$DESeq_full_results %>%
	mutate(treatment = "Paclitaxel", batch = 2)
full_DESeq = rbind(full_DESeq, temp$DESeq_full_results)

temp$DESeq_summary = temp$DESeq_summary %>% 
	mutate(treatment = "Paclitaxel", batch = 2)
summary_stats = rbind(summary_stats, temp$DESeq_summary)
```

## Ruxolibinib

```{r}
exp_info = tribble(
	~files, ~batch, ~rep, ~treatment,
	
	here('salmon_alignments/batch_02/rep_01/DMSO/quant.sf'), 2, 1, "DMSO",
	here('salmon_alignments/batch_02/rep_01/Rux/quant.sf'), 2, 1, "Rux",
	here('salmon_alignments/batch_02/rep_02/DMSO/quant.sf'), 2, 2, "DMSO",
	here('salmon_alignments/batch_02/rep_02/Rux/quant.sf'), 2, 2, "Rux"
)

temp = collect_all_DESeq(exp_info)
temp$DESeq_full_results = temp$DESeq_full_results %>%
	mutate(treatment = "Ruxolibinib", batch = 2)
full_DESeq = rbind(full_DESeq, temp$DESeq_full_results)

temp$DESeq_summary = temp$DESeq_summary %>% 
	mutate(treatment = "Ruxolibinib", batch = 2)
summary_stats = rbind(summary_stats, temp$DESeq_summary)
```

## SGCCP30

```{r}
exp_info = tribble(
	~files, ~batch, ~rep, ~treatment,
	
	here('salmon_alignments/batch_02/rep_01/DMSO/quant.sf'), 2, 1, "DMSO",
	here('salmon_alignments/batch_02/rep_01/SGC/quant.sf'), 2, 1, "SGC",
	here('salmon_alignments/batch_02/rep_02/DMSO/quant.sf'), 2, 2, "DMSO",
	here('salmon_alignments/batch_02/rep_02/SGC/quant.sf'), 2, 2, "SGC"
)

temp = collect_all_DESeq(exp_info)
temp$DESeq_full_results = temp$DESeq_full_results %>%
	mutate(treatment = "SGCCP30", batch = 2)
full_DESeq = rbind(full_DESeq, temp$DESeq_full_results)

temp$DESeq_summary = temp$DESeq_summary %>% 
	mutate(treatment = "SGCCP30", batch = 2)
summary_stats = rbind(summary_stats, temp$DESeq_summary)
```

# Batch 3

## Alisertib

```{r}
exp_info = tribble(
	~files, ~batch, ~rep, ~treatment,
	
	here('salmon_alignments/batch_03/rep_01/DMSO/quant.sf'), 3, 1, "DMSO",
	here('salmon_alignments/batch_03/rep_01/Alis/quant.sf'), 3, 1, "Alis",
	here('salmon_alignments/batch_03/rep_02/DMSO/quant.sf'), 3, 2, "DMSO",
	here('salmon_alignments/batch_03/rep_02/Alis/quant.sf'), 3, 2, "Alis"
)

temp = collect_all_DESeq(exp_info)
temp$DESeq_full_results = temp$DESeq_full_results %>%
	mutate(treatment = "Alisertib", batch = 3)
full_DESeq = rbind(full_DESeq, temp$DESeq_full_results)

temp$DESeq_summary = temp$DESeq_summary %>% 
	mutate(treatment = "Alisertib", batch = 3)
summary_stats = rbind(summary_stats, temp$DESeq_summary)
```

## Bortezomib

```{r}
exp_info = tribble(
	~files, ~batch, ~rep, ~treatment,
	
	here('salmon_alignments/batch_03/rep_01/DMSO/quant.sf'), 3, 1, "DMSO",
	here('salmon_alignments/batch_03/rep_01/Bort/quant.sf'), 3, 1, "Bort",
	here('salmon_alignments/batch_03/rep_02/DMSO/quant.sf'), 3, 2, "DMSO",
	here('salmon_alignments/batch_03/rep_02/Bort/quant.sf'), 3, 2, "Bort"
)

temp = collect_all_DESeq(exp_info)
temp$DESeq_full_results = temp$DESeq_full_results %>%
	mutate(treatment = "Bortezomib", batch = 3)
full_DESeq = rbind(full_DESeq, temp$DESeq_full_results)

temp$DESeq_summary = temp$DESeq_summary %>% 
	mutate(treatment = "Bortezomib", batch = 3)
summary_stats = rbind(summary_stats, temp$DESeq_summary)
```

## CoCl2

```{r}
exp_info = tribble(
	~files, ~batch, ~rep, ~treatment,
	
	here('salmon_alignments/batch_03/rep_01/DMSO/quant.sf'), 3, 1, "DMSO",
	here('salmon_alignments/batch_03/rep_01/CoCl2/quant.sf'), 3, 1, "CoCl2",
	here('salmon_alignments/batch_03/rep_02/DMSO/quant.sf'), 3, 2, "DMSO",
	here('salmon_alignments/batch_03/rep_02/CoCl2/quant.sf'), 3, 2, "CoCl2"
)

temp = collect_all_DESeq(exp_info)
temp$DESeq_full_results = temp$DESeq_full_results %>%
	mutate(treatment = "CoCl2", batch = 3)
full_DESeq = rbind(full_DESeq, temp$DESeq_full_results)

temp$DESeq_summary = temp$DESeq_summary %>% 
	mutate(treatment = "CoCl2", batch = 3)
summary_stats = rbind(summary_stats, temp$DESeq_summary)
```

## FCCP

```{r}
exp_info = tribble(
	~files, ~batch, ~rep, ~treatment,
	
	here('salmon_alignments/batch_03/rep_01/DMSO/quant.sf'), 3, 1, "DMSO",
	here('salmon_alignments/batch_03/rep_01/FCCP/quant.sf'), 3, 1, "FCCP",
	here('salmon_alignments/batch_03/rep_02/DMSO/quant.sf'), 3, 2, "DMSO",
	here('salmon_alignments/batch_03/rep_02/FCCP/quant.sf'), 3, 2, "FCCP"
)

temp = collect_all_DESeq(exp_info)
temp$DESeq_full_results = temp$DESeq_full_results %>%
	mutate(treatment = "FCCP", batch = 3)
full_DESeq = rbind(full_DESeq, temp$DESeq_full_results)

temp$DESeq_summary = temp$DESeq_summary %>% 
	mutate(treatment = "FCCP", batch = 3)
summary_stats = rbind(summary_stats, temp$DESeq_summary)
```

## Palbociclib

```{r}
exp_info = tribble(
	~files, ~batch, ~rep, ~treatment,
	
	here('salmon_alignments/batch_03/rep_01/DMSO/quant.sf'), 3, 1, "DMSO",
	here('salmon_alignments/batch_03/rep_01/Palbo/quant.sf'), 3, 1, "Palbo",
	here('salmon_alignments/batch_03/rep_02/DMSO/quant.sf'), 3, 2, "DMSO",
	here('salmon_alignments/batch_03/rep_02/Palbo/quant.sf'), 3, 2, "Palbo"
)

temp = collect_all_DESeq(exp_info)
temp$DESeq_full_results = temp$DESeq_full_results %>%
	mutate(treatment = "Palbociclib", batch = 3)
full_DESeq = rbind(full_DESeq, temp$DESeq_full_results)

temp$DESeq_summary = temp$DESeq_summary %>% 
	mutate(treatment = "Palbociclib", batch = 3)
summary_stats = rbind(summary_stats, temp$DESeq_summary)
```

# DMSO Comparisons

## DMSO 1 vs DMSO 2

```{r}
exp_info = tribble(
	~files, ~batch, ~rep, ~treatment,
	
	here('salmon_alignments/batch_01/rep_01/DMSO/quant.sf'), 1, 1, "DMSO",
	here('salmon_alignments/batch_01/rep_02/DMSO/quant.sf'), 1, 2, "DMSO",
	here('salmon_alignments/batch_02/rep_01/DMSO/quant.sf'), 2, 1, "DMSO 2",
	here('salmon_alignments/batch_02/rep_02/DMSO/quant.sf'), 2, 2, "DMSO 2"
)

temp = collect_all_DESeq(exp_info)
temp$DESeq_full_results = temp$DESeq_full_results %>%
	mutate(treatment = "DMSO 1 vs DMSO 2", batch = 1)
full_DESeq = rbind(full_DESeq, temp$DESeq_full_results)

temp$DESeq_summary = temp$DESeq_summary %>% 
	mutate(treatment = "DMSO 1 vs DMSO 2", batch = 1)
summary_stats = rbind(summary_stats, temp$DESeq_summary)
```

## DMSO 1 vs DMSO 3

```{r}
exp_info = tribble(
	~files, ~batch, ~rep, ~treatment,
	
	here('salmon_alignments/batch_01/rep_01/DMSO/quant.sf'), 1, 1, "DMSO",
	here('salmon_alignments/batch_01/rep_02/DMSO/quant.sf'), 1, 2, "DMSO",
	here('salmon_alignments/batch_03/rep_01/DMSO/quant.sf'), 3, 1, "DMSO 3",
	here('salmon_alignments/batch_03/rep_02/DMSO/quant.sf'), 3, 2, "DMSO 3",
	
)

temp = collect_all_DESeq(exp_info)
temp$DESeq_full_results = temp$DESeq_full_results %>%
	mutate(treatment = "DMSO 1 vs DMSO 3", batch = 1)
full_DESeq = rbind(full_DESeq, temp$DESeq_full_results)

temp$DESeq_summary = temp$DESeq_summary %>% 
	mutate(treatment = "DMSO 1 vs DMSO 3", batch = 1)
summary_stats = rbind(summary_stats, temp$DESeq_summary)
```

## DMSO 2 vs DMSO 3

```{r}
exp_info = tribble(
	~files, ~batch, ~rep, ~treatment,
	
	here('salmon_alignments/batch_02/rep_01/DMSO/quant.sf'), 2, 1, "DMSO",
	here('salmon_alignments/batch_02/rep_02/DMSO/quant.sf'), 2, 2, "DMSO",
	here('salmon_alignments/batch_03/rep_01/DMSO/quant.sf'), 3, 1, "DMSO 3",
	here('salmon_alignments/batch_03/rep_02/DMSO/quant.sf'), 3, 2, "DMSO 3"
)

temp = collect_all_DESeq(exp_info)
temp$DESeq_full_results = temp$DESeq_full_results %>%
	mutate(treatment = "DMSO 2 vs DMSO 3", batch = 1)
full_DESeq = rbind(full_DESeq, temp$DESeq_full_results)

temp$DESeq_summary = temp$DESeq_summary %>% 
	mutate(treatment = "DMSO 2 vs DMSO 3", batch = 1)
summary_stats = rbind(summary_stats, temp$DESeq_summary)
```

# Summary Output

```{r}
summary_stats_output = summary_stats %>% 
	select(treatment,batch,everything()) %>% 
	rename("Genes" = number_2fold,
				 "Kinases" = num_kinases,
				 "Dark Kinases" = num_dark_kinases,
				 "IDG Kinases" = dk_diff_str)

write_csv(summary_stats_output,here('DESeq_results/SUM159_DESeq2_summary.csv'))

write_csv(full_DESeq, here('DESeq_results/SUM159_full_DESeq2.csv.gz'))
```