---
title: "Drug Pertubations - DESeq2 Analysis - SUM159"
author: "Matthew Berginski"
date: "2/17/2020"
output: html_document
---

```{r setup, include=FALSE}
library(tximport)
library("DESeq2")

library(DarkKinaseTools)
library(here)
library(tidyverse)
library(glue)
library(tictoc)

source(here('shared_functions.R'))
```

```{r}
tic()
exp_info = tribble(
	~files, ~batch, ~rep, ~treatment,
	
	here('salmon_alignments/batch_01/rep_01/DMSO/quant.sf'), 1, 1, "DMSO",
	here('salmon_alignments/batch_01/rep_02/DMSO/quant.sf'), 1, 2, "DMSO",
	here('salmon_alignments/batch_01/rep_01/Dinac/quant.sf'), 1, 1, "Dina",
	here('salmon_alignments/batch_01/rep_02/Dinac/quant.sf'), 1, 2, "Dina",
	here('salmon_alignments/batch_01/rep_01/Ent/quant.sf'), 1, 1, "Ent",
	here('salmon_alignments/batch_01/rep_02/Ent/quant.sf'), 1, 2, "Ent",
	here('salmon_alignments/batch_01/rep_01/JIB04/quant.sf'), 1, 1, "JIB.04.low",
	here('salmon_alignments/batch_01/rep_02/JIB04/quant.sf'), 1, 2, "JIB.04.low",
	here('salmon_alignments/batch_01/rep_01/MK2206/quant.sf'), 1, 1, "MK2206",
	here('salmon_alignments/batch_01/rep_02/MK2206/quant.sf'), 1, 2, "MK2206",
	here('salmon_alignments/batch_01/rep_01/Tram/quant.sf'), 1, 1, "Tram",
	here('salmon_alignments/batch_01/rep_02/Tram/quant.sf'), 1, 2, "Tram",
	
	here('salmon_alignments/batch_02/rep_01/DMSO/quant.sf'), 2, 1, "DMSO",
	here('salmon_alignments/batch_02/rep_02/DMSO/quant.sf'), 2, 2, "DMSO",
	here('salmon_alignments/batch_02/rep_01/JIB04/quant.sf'), 2, 1, "JIB.04.high",
	here('salmon_alignments/batch_02/rep_02/JIB04/quant.sf'), 2, 2, "JIB.04.high",
	here('salmon_alignments/batch_02/rep_01/Navi/quant.sf'), 2, 1, "Navitoclax",
	here('salmon_alignments/batch_02/rep_02/Navi/quant.sf'), 2, 2, "Navitoclax",
	here('salmon_alignments/batch_02/rep_01/Paclit/quant.sf'), 2, 1, "Paclitaxel",
	here('salmon_alignments/batch_02/rep_02/Paclit/quant.sf'), 2, 2, "Paclitaxel",
	here('salmon_alignments/batch_02/rep_01/Rux/quant.sf'), 2, 1, "Ruxolitinib",
	here('salmon_alignments/batch_02/rep_02/Rux/quant.sf'), 2, 2, "Ruxolitinib",
	here('salmon_alignments/batch_02/rep_01/SGC/quant.sf'), 2, 1, "SGCCP30",
	here('salmon_alignments/batch_02/rep_02/SGC/quant.sf'), 2, 2, "SGCCP30",

	here('salmon_alignments/batch_03/rep_01/DMSO/quant.sf'), 3, 1, "DMSO",
	here('salmon_alignments/batch_03/rep_02/DMSO/quant.sf'), 3, 2, "DMSO",	
	here('salmon_alignments/batch_03/rep_01/Alis/quant.sf'), 3, 1, "Alisertib",
	here('salmon_alignments/batch_03/rep_02/Alis/quant.sf'), 3, 2, "Alisertib",
	here('salmon_alignments/batch_03/rep_01/Bort/quant.sf'), 3, 1, "Bortezomib",
	here('salmon_alignments/batch_03/rep_02/Bort/quant.sf'), 3, 2, "Bortezomib",
	here('salmon_alignments/batch_03/rep_01/CoCl2/quant.sf'), 3, 1, "CoCl2",
	here('salmon_alignments/batch_03/rep_02/CoCl2/quant.sf'), 3, 2, "CoCl2",
	here('salmon_alignments/batch_03/rep_01/FCCP/quant.sf'), 3, 1, "FCCP",
	here('salmon_alignments/batch_03/rep_02/FCCP/quant.sf'), 3, 2, "FCCP",
	here('salmon_alignments/batch_03/rep_01/Palbo/quant.sf'), 3, 1, "Palbociclib",
	here('salmon_alignments/batch_03/rep_02/Palbo/quant.sf'), 3, 2, "Palbociclib",
)

dds_analysis = get_DESeq_analysis(exp_info, DESeq_design = ~batch + treatment)
DESeq_results = collect_full_DESeq_and_summary(dds_analysis)

write_csv(DESeq_results$full,here('DESeq_results/SUM159_only_DESeq2_results.csv.gz'))
write_csv(DESeq_results$summary,here('DESeq_results/SUM159_only_DESeq2_summary.csv'))
toc()
```