---
title: "Drug Pertubations - DESeq2 Analysis - SUM159"
author: "Matthew Berginski"
date: "2/17/2020"
output: html_document
---

```{r setup, include=FALSE}
library(tximport)
library("DESeq2")

library(DarkKinaseTools)
library(here)
library(tidyverse)
library(glue)
library(tictoc)

source(here('shared_functions.R'))
```


```{r}
exp_info = tribble(
	~files, ~batch, ~rep, ~treatment,
	
	here('salmon_alignments/MDAMB468/rep_01/DMSO/quant.sf'), 1, 1, "DMSO",
	here('salmon_alignments/MDAMB468/rep_02/DMSO/quant.sf'), 1, 2, "DMSO",
	here('salmon_alignments/MDAMB468/rep_01/Bort/quant.sf'), 1, 1, "Bort",
	here('salmon_alignments/MDAMB468/rep_02/Bort/quant.sf'), 1, 2, "Bort",
	here('salmon_alignments/MDAMB468/rep_01/JIB04/quant.sf'), 1, 1, "JIB04",
	here('salmon_alignments/MDAMB468/rep_02/JIB04/quant.sf'), 1, 2, "JIB04",
	here('salmon_alignments/MDAMB468/rep_01/MK2206/quant.sf'), 1, 1, "MK2206",
	here('salmon_alignments/MDAMB468/rep_02/MK2206/quant.sf'), 1, 2, "MK2206",
	here('salmon_alignments/MDAMB468/rep_01/Palbo/quant.sf'), 1, 1, "Palbo",
	here('salmon_alignments/MDAMB468/rep_02/Palbo/quant.sf'), 1, 2, "Palbo",
	here('salmon_alignments/MDAMB468/rep_01/Tram/quant.sf'), 1, 1, "Tram",
	here('salmon_alignments/MDAMB468/rep_02/Tram/quant.sf'), 1, 2, "Tram",
)

dds_analysis = get_DESeq_analysis(exp_info, DESeq_design = ~treatment)
DESeq_results = collect_full_DESeq_and_summary(dds_analysis)

write_csv(DESeq_results$full,here('DESeq_results/MDAMB468_only_DESeq2_results.csv.gz'))
write_csv(DESeq_results$summary,here('DESeq_results/MDAMB468_only_DESeq2_summary.csv'))
```