---
title: "DESeq2 Output Clustering"
author: "Matthew Berginski"
date: "3/23/2020"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(ggdendro)
library(here)
library(umap)
library(broom)
library(tictoc)
library(ggforce)

library(BerginskiRMisc)
library(DarkKinaseTools)
```

# Read in DESeq2 Normalized Log Changes

```{r read in data, cache=TRUE, include=FALSE}
DESeq_ratios = read_csv(here('DESeq2_results.csv.gz'))
```

## Data Organizing/Filtering

```{r data organization, cache=TRUE, include=FALSE}
high_missing_ratio_kinases = DESeq_ratios %>%
	filter(hgnc_symbol %in% all_kinases$symbol,is.na(log2FoldChange)) %>%
	count(hgnc_symbol) %>%
	filter(n > 2) %>%
	pull(hgnc_symbol)

drug_perturb_ratio_wide_kinases = DESeq_ratios %>%
	filter(hgnc_symbol %in% all_kinases$symbol & ! hgnc_symbol %in% high_missing_ratio_kinases) %>%
	mutate(treatment_batch = paste0(treatment,'_',batch)) %>%
	select(treatment_batch,hgnc_symbol,log2FoldChange) %>%
	mutate(log2FoldChange = ifelse(is.na(log2FoldChange), 0, log2FoldChange)) %>%
	pivot_wider(names_from = treatment_batch, values_from = log2FoldChange)

drug_perturb_ratio_wide_experiments = DESeq_ratios %>%
	filter(hgnc_symbol %in% all_kinases$symbol & ! hgnc_symbol %in% high_missing_ratio_kinases) %>%
	select(treatment,hgnc_symbol,log2FoldChange) %>%
	mutate(log2FoldChange = ifelse(is.na(log2FoldChange), 0, log2FoldChange)) %>%
	pivot_wider(names_from = hgnc_symbol, values_from = log2FoldChange)
```

## Experiment UMAP Vis

```{r experiment UMAP, cache=TRUE, include=FALSE}
experiment_correlations_ratio = amap::Dist(drug_perturb_ratio_wide_experiments %>% 
																			 	column_to_rownames(var = "treatment"),
																			 method="correlation")

umap_settings = umap.defaults
umap_settings$init = "dist"

experiment_correlations_ratio_umap = experiment_correlations_ratio %>%
	as.matrix() %>%
	umap(config = umap_settings) %>%
	identity()

experiment_umap_plot = data.frame(umap_1 = experiment_correlations_ratio_umap$layout[,1],
															 umap_2 = experiment_correlations_ratio_umap$layout[,2],
															 experiment = drug_perturb_ratio_wide_experiments$treatment)

library(ggrepel)
library(BerginskiRMisc)
ggplot(experiment_umap_plot, aes(x=umap_1,y=umap_2,label = experiment)) +
	geom_point(alpha=0.75) + theme_berginski() + xlab('UMAP 1') + ylab('UMAP 2') +
	geom_text_repel(
		segment.size  = 0.2,
    segment.color = "grey50",
    force = 10)
ggsave(here('figures/clustering/experiment_correlation_umap.png'))
```

```{r correlation histogram}
correlation_vals = data.frame(
	cor_vals = as.vector((experiment_correlations_ratio - 1)*-1)
)

ggplot(correlation_vals, aes(x=cor_vals)) + 
	geom_histogram() +
	xlab('Pairwise Treatment Correlations') +
	ylab('') +
	geom_vline(aes(xintercept = mean(cor_vals)), color='red') +
	theme_berginski()
ggsave(here('figures/clustering/experiment_correlation_vals.png'),height=4,width=4)
```

```{r, cache=TRUE, include=FALSE}
experiment_cluster_ratio = hclust(experiment_correlations_ratio)

dd.row <- as.dendrogram(experiment_cluster_ratio)
ddata_x <- dendro_data(dd.row)

dendro_labels = label(ddata_x)
```

```{r experiment cluster plot}
ggplot(segment(ddata_x)) +
	geom_segment(aes(x=x, y=y, xend=xend, yend=yend)) +
	geom_text(data = dendro_labels,
						aes(label = label, x=x,y=0), angle=90, hjust=1.1) +
	# ylim(c(-1,NA)) +
	xlab('') +
	theme_berginski() +
	theme(axis.title.x=element_blank(),
				axis.text.x=element_blank(),
				axis.ticks.x=element_blank()) +
	# scale_y_discrete("Correlation Distance", waiver(), waiver(), c(0,2)) +
	scale_y_continuous("Kinase Correlation Distance", breaks = c(0,0.5,1), limits = c(-0.8,NA))
	NULL
ggsave(here('figures/clustering/experiment_cluster_tree.png'),height=4,width=4)
trimImage(here('figures/clustering/experiment_cluster_tree.png'))
```

### UMAP on DESeq Log2 fold Results

```{r}
umap_settings = umap.defaults
umap_settings$min_dist = 0.01

kinase_correlations_ratio_umap = drug_perturb_ratio_wide_kinases %>%
	column_to_rownames(var='hgnc_symbol') %>%
	umap() %>%
	identity()

kinase_ratio_plot = data.frame(umap_1 = kinase_correlations_ratio_umap$layout[,1],
															 umap_2 = kinase_correlations_ratio_umap$layout[,2],
															 symbol = drug_perturb_ratio_wide_kinases$hgnc_symbol) %>%
	left_join(all_kinases %>% select(symbol, class)) %>%
	mutate(label = case_when(
		# class == "Dark" ~ symbol,
		symbol == "PKMYT1" ~ symbol,
		symbol == "TLK2" ~ symbol,
		symbol == "CDK12" ~ symbol,
		symbol == "CDK13" ~ symbol,
		# symbol == "PIP5K1B" ~ symbol,
		TRUE ~ ""
	))

library(ggrepel)
library(BerginskiRMisc)
ggplot(kinase_ratio_plot, aes(x=umap_1,y=umap_2,color = class,label = label)) +
	geom_point(alpha=0.75) + theme_berginski() + xlab('UMAP 1') + ylab('UMAP 2') +
	geom_text_repel(
		segment.size  = 0.2,
    segment.color = "grey50",
    force = 10)
ggsave(here('figures/clustering/kinase_cluster_ratio_umap.png'))
```


```{r}
kinase_correlations_ratio = amap::Dist(drug_perturb_ratio_wide_kinases %>% 
																			 	column_to_rownames(var = "hgnc_symbol"),
																			 method="correlation")

kinase_correlations_ratio = amap::Dist(drug_perturb_ratio_wide_kinases %>% 
																			 	column_to_rownames(var = "hgnc_symbol"),
																			 method="correlation",upper=T)
```

```{r}
umap_settings = umap.defaults
umap_settings$min_dist = 0.001
umap_settings$n_neighbors = 10
umap_settings$random_state = 1234
umap_settings$input = "dist"

kinase_correlations_ratio_umap = kinase_correlations_ratio %>%
	as.matrix() %>%
	umap(config = umap_settings)

kinase_ratio_plot = data.frame(umap_1 = kinase_correlations_ratio_umap$layout[,1],
															 umap_2 = kinase_correlations_ratio_umap$layout[,2],
															 symbol = drug_perturb_ratio_wide_kinases$hgnc_symbol) %>%
	left_join(all_kinases %>% select(symbol, class)) %>%
	mutate(label = case_when(
        # class == "Dark" ~ symbol,
        symbol == "PKMYT1" ~ symbol,
        symbol == "TLK2" ~ symbol,
        # symbol == "BRSK2" ~ symbol,
        symbol == "CDK12" ~ symbol,
        symbol == "CDK13" ~ symbol,
        symbol == "SBK1" ~ symbol,
        symbol == "CDC42BPG" ~ symbol,
        symbol == "PAK3" ~ symbol,
        # symbol == "PIP5K1B" ~ symbol,
        TRUE ~ ""
    )) %>%
	identity()

library(ggrepel)
library(BerginskiRMisc)
ggplot(kinase_ratio_plot, aes(x=umap_1, y=umap_2, label = label,  color = class)) +
	geom_point(alpha = 0.75) + theme_berginski() + xlab('UMAP 1') + ylab('UMAP 2') +
	geom_text_repel(
		segment.size  = 1,
    segment.color = "grey50",
    force = 20,
		show.legend = FALSE) +
	scale_color_discrete(name="Kinase Type")
ggsave(here('figures/clustering/kinase_cluster_ratio_correlation_umap.png'))

```

```{r, include = F}
kinase_correlations_ratio = amap::Dist(drug_perturb_ratio_wide_kinases %>% 
																			 	column_to_rownames(var = "hgnc_symbol"),
																			 method="correlation")

kinase_cluster_ratio = hclust(kinase_correlations_ratio)

dd.row <- as.dendrogram(kinase_cluster_ratio)
ddata_x <- dendro_data(dd.row)

dendro_labels = label(ddata_x) %>% left_join(all_kinases %>% select(symbol,class), by=c('label'='symbol'))

end_points = ddata_x$segments %>% filter(yend == 0) %>%
	left_join(dendro_labels, by=c('x'='x'))

ggplot(segment(ddata_x)) +
	geom_segment(aes(x=x, y=y, xend=xend, yend=yend)) +
	# geom_text(data = dendro_labels,
	# 					aes(label = label, x=x,y=0, color = class), angle=90, hjust=1) +
	# ylim(c(-0.5,2)) +
	# geom_hline(aes(yintercept = 1.2), color='red') +
	xlab('') +
	# geom_point(data = end_points, mapping = aes(x=xend,y=yend-0.02, color=class),shape='\u007C') +
	geom_rect(data = end_points, mapping = aes(xmin=xend-0.5,xmax=xend+0.5,ymin=yend-0.25,ymax=yend-0.01,fill=class)) +
	theme_berginski() +
	theme(axis.title.x=element_blank(),
				axis.text.x=element_blank(),
				axis.ticks.x=element_blank()) +
	scale_y_continuous(name = "Correlation Distance",breaks=seq(0,2,by=0.5)) +
	scale_x_continuous(name = "",expand=c(0,0)) +
	scale_fill_discrete(name = "Kinase Type")

ggsave(here('figures/clustering/kinase_clustering_DESeq_correlation.png'),width=10*0.9,height=3*0.9,dpi = 300)
trimImage(here('figures/clustering/kinase_clustering_DESeq_correlation.png'))
```

## Output Kinase Cluster Lists

```{r}
kinase_hier_clusters = as.data.frame(cutree(kinase_cluster_ratio,k = 15))
names(kinase_hier_clusters) <- "cluster_num"
kinase_hier_clusters = kinase_hier_clusters %>%
	rownames_to_column(var = "hgnc_symbol") %>%
	arrange(cluster_num, hgnc_symbol) %>%
	left_join(all_kinases %>% select(class, symbol), by=c('hgnc_symbol'='symbol')) %>%
	write_csv(here('cluster_sets/DESeq_kinase_correlation_clusters.csv'))

kinase_cluster_counts = kinase_hier_clusters %>% 
	count(cluster_num, name = "Total Kinases") %>%
	left_join(kinase_hier_clusters %>% filter(class == "Dark") %>% count(cluster_num, name="Understudied Count")) %>%
	left_join(kinase_hier_clusters %>% filter(class == "Light") %>% count(cluster_num, name="Well Studied Count")) %>%
	write_csv(here('cluster_sets/DESeq_kinase_correlation_counts.csv'))
```

```{r}
library(gridExtra)

p<-tableGrob(kinase_hier_clusters %>% 
						 	group_by(cluster_num,class) %>% 
						 	count() %>% 
						 	pivot_wider(names_from = 'class',values_from = n) %>%
						 	rename('Cluster Number'="cluster_num"),
						 rows = NULL)
grid.arrange(p)
ggsave(here('figures/clustering/kinase_clustering_table.png'),p)
trimImage(here('figures/clustering/kinase_clustering_table.png'))

```

```{r}
end_points_clusters = end_points %>% left_join(kinase_hier_clusters, by=c('label' = 'hgnc_symbol'))

ggplot(segment(ddata_x)) +
	geom_segment(aes(x=x, y=y, xend=xend, yend=yend)) +
	# geom_text(data = dendro_labels,
	# 					aes(label = label, x=x,y=0, color = class), angle=90, hjust=1) +
	# ylim(c(-0.5,2)) +
	# geom_hline(aes(yintercept = 1.2), color='red') +
	xlab('') +
	# geom_point(data = end_points, mapping = aes(x=xend,y=yend-0.02, color=class),shape='\u007C') +
	# geom_rect(data = end_points, mapping = aes(xmin=xend-0.5,xmax=xend+0.5,ymin=yend-0.25,ymax=yend-0.01,fill=class)) +
	geom_rect(data = end_points_clusters, 
						mapping = aes(xmin=xend-0.5, 
													xmax=xend+0.5, 
													ymin=yend-0.01,
													ymax=yend-0.25,
													fill=as.factor(cluster_num))) +
	theme_berginski() +
	theme(axis.title.x=element_blank(),
				axis.text.x=element_blank(),
				axis.ticks.x=element_blank()) +
	scale_y_continuous(name = "Correlation Distance",breaks=seq(0,2,by=0.5)) +
	scale_x_continuous(name = "",expand=c(0,0)) +
	scale_fill_discrete(name = "Kinase Cluster")

ggsave(here('figures/clustering/kinase_clustering_cluster_color.png'),width=10,dpi = 300)
trimImage(here('figures/clustering/kinase_clustering_cluster_color.png'))

```

```{r}
umap_settings = umap.defaults
umap_settings$min_dist = 0.01
umap_settings$input = "dist"

kinase_correlations_ratio_umap = kinase_correlations_ratio %>%
	as.matrix() %>%
	umap(config = umap_settings)

kinase_ratio_plot = data.frame(umap_1 = kinase_correlations_ratio_umap$layout[,1],
															 umap_2 = kinase_correlations_ratio_umap$layout[,2],
															 symbol = drug_perturb_ratio_wide_kinases$hgnc_symbol) %>%
	left_join(all_kinases %>% select(symbol, class)) %>%
	left_join(kinase_hier_clusters %>% select(hgnc_symbol,cluster_num), by = c('symbol'='hgnc_symbol')) %>%
	mutate(label = case_when(
        # class == "Dark" ~ symbol,
        symbol == "PKMYT1" ~ symbol,
        symbol == "TLK2" ~ symbol,
        symbol == "BRSK2" ~ symbol,
        symbol == "CDK12" ~ symbol,
        symbol == "CDK13" ~ symbol,
        # symbol == "PIP5K1B" ~ symbol,
        TRUE ~ ""
    ))


library(ggrepel)
library(BerginskiRMisc)
ggplot(kinase_ratio_plot, aes(x=umap_1,y=umap_2,label = label, color=as.factor(cluster_num))) +
	geom_point() + theme_berginski() + xlab('UMAP 1') + ylab('UMAP 2') +
	geom_text_repel(
		segment.size  = 0.2,
    segment.color = "grey50",
    force = 10)
ggsave(here('figures/clustering/kinase_cluster_ratio_umap.png'))
```

## Output Kinase Cluster Lists

```{r}
kinase_hier_clusters = as.data.frame(cutree(kinase_cluster_ratio,k = 15))
names(kinase_hier_clusters) <- "cluster_num"
kinase_hier_clusters = kinase_hier_clusters %>%
	rownames_to_column(var = "hgnc_symbol") %>%
	arrange(cluster_num, hgnc_symbol) %>%
	left_join(all_kinases %>% select(class, symbol), by=c('hgnc_symbol'='symbol')) %>%
	write_csv(here('cluster_sets/DESeq_kinase_correlation_clusters.csv'))

kinase_cluster_counts = kinase_hier_clusters %>% 
	count(cluster_num, name = "Total Kinases") %>%
	left_join(kinase_hier_clusters %>% filter(class == "Dark") %>% count(cluster_num, name="Understudied Count")) %>%
	left_join(kinase_hier_clusters %>% filter(class == "Light") %>% count(cluster_num, name="Well Studied Count")) %>%
	write_csv(here('cluster_sets/DESeq_kinase_correlation_counts.csv'))
```

## Visualize Changes in Kinase Expression

```{r cluster_profiles}
kinase_DESeq_ratios_clusters = DESeq_ratios %>% right_join(kinase_hier_clusters)

treatment_summary = kinase_DESeq_ratios_clusters %>% 
	group_by(treatment) %>%
	summarise(mean_log2 = mean(log2FoldChange,na.rm=T),
						lower_log2 = tidy(t.test(log2FoldChange))$conf.low,
						upper_log2 = tidy(t.test(log2FoldChange))$conf.high)

cluster_treatment_summary = kinase_DESeq_ratios_clusters %>%
	group_by(cluster_num,treatment) %>% 
	summarise(mean_log2 = mean(log2FoldChange,na.rm=T),
						lower_log2 = tidy(t.test(log2FoldChange))$conf.low,
						upper_log2 = tidy(t.test(log2FoldChange))$conf.high)

for (this_cluster in sort(unique(kinase_hier_clusters$cluster_num))) {
	this_plot = ggplot(kinase_DESeq_ratios_clusters %>% filter(cluster_num == this_cluster), 
			 aes(x=treatment,y=log2FoldChange)) + 
	# geom_jitter() +
	geom_line(aes(group = hgnc_symbol),alpha=0.2) +
	geom_point(data = cluster_treatment_summary %>% filter(cluster_num == this_cluster),
						 aes(x=treatment,y=mean_log2), color='blue') +
	geom_point(data = treatment_summary, aes(x=treatment,y=mean_log2), color='red') +
	theme(axis.text.x=element_text(angle = -90, hjust = 0,vjust=0.5)) +
	xlab('') +
	ylab('Log 2 Fold Expression Change') +
	scale_color_discrete(name="Gene") +
	ggtitle(paste('Drug Response Profile for Cluster: ', this_cluster)) +
	theme_berginski()
	# 
	# this_plot = ggplot(cluster_treatment_summary %>% filter(cluster_num == this_cluster),
	# 									 aes(x=treatment,y=mean_log2, group=cluster_num)) +
	# 	geom_pointrange(aes(ymin=lower_log2,ymax=upper_log2)) +
	# 	ggtitle(paste('Drug Response Profile for Cluster: ', this_cluster)) +
	# 	
	# 	geom_pointrange(data = treatment_summary, 
	# 									aes(ymin=lower_log2,ymax=lower_log2, group='overall'), color='blue',alpha=0.25) +
	# 	
	# 	theme_berginski() +
	# 	xlab('') +
	# 	ylab('Average Shrunk Log2 Fold Change') +
	# 	ylim(c(-2.5,2.5))
	print(this_plot)
}
```

```{r}
library(gghighlight)
ggplot(kinase_DESeq_ratios_clusters %>% filter(cluster_num == 11), 
			 aes(x=treatment,y=log2FoldChange)) + 
	# geom_jitter() +
	geom_line(aes(group = hgnc_symbol, color=hgnc_symbol)) +
	gghighlight(hgnc_symbol == "PKMYT1" | 
						  hgnc_symbol == "CDK11B" | 
							hgnc_symbol == "NEK4", use_direct_label = FALSE) +
	geom_point(data = cluster_treatment_summary %>% filter(cluster_num == 11),
						 aes(x=treatment,y=mean_log2), color='blue',alpha=0.5) +
	theme(axis.text.x=element_text(angle = -90, hjust = 0,vjust=0.5)) +
	xlab('') +
	ylab('Log 2 Fold Expression Change') +
	scale_color_discrete(name="Gene") +
	# facet_wrap(~hgnc_symbol) +
	theme_berginski()
ggsave(here('figures/clustering/kinase_cluster_11.png'))

kinase_DESeq_ratios_clusters %>% 
	filter(cluster_num == 11) %>% 
	group_by(hgnc_symbol) %>% 
	summarise(mean_log2 = mean(log2FoldChange, na.rm=T)) %>%
	write_csv(here('cluster_sets/kinase_cluster_11.csv'))
```

```{r}
library(gghighlight)
ggplot(kinase_DESeq_ratios_clusters %>% filter(cluster_num == 6), 
			 aes(x=treatment,y=log2FoldChange)) + 
	# geom_jitter() +
	geom_line(aes(group = hgnc_symbol, color=hgnc_symbol)) +
	gghighlight(hgnc_symbol == "CDK18" |
							hgnc_symbol == "CDK19" |
							hgnc_symbol == "SBK1", use_direct_label = FALSE) +
	geom_point(data = cluster_treatment_summary %>% filter(cluster_num == 6),
						 aes(x=treatment,y=mean_log2), color='blue',alpha=0.5) +
	geom_point(data = treatment_summary,
						 aes(x=treatment,y=mean_log2), color='red',alpha=0.5) +
	theme(axis.text.x=element_text(angle = -90, hjust = 0,vjust=0.5)) +
	xlab('') +
	ylab('Log 2 Fold Expression Change') +
	scale_color_discrete(name="Gene") +
	# facet_wrap(~hgnc_symbol) +
	theme_berginski()

ggsave(here('figures/clustering/kinase_cluster_6.png'))

kinase_DESeq_ratios_clusters %>% 
	filter(cluster_num == 6) %>% 
	group_by(hgnc_symbol) %>% 
	summarise(mean_log2 = mean(log2FoldChange, na.rm=T)) %>%
	write_csv(here('cluster_sets/kinase_cluster_06.csv'))
```

```{r}
library(gghighlight)
ggplot(kinase_DESeq_ratios_clusters %>% filter(cluster_num == 8), 
			 aes(x=treatment,y=log2FoldChange)) + 
	# geom_jitter() +
	geom_line(aes(group = hgnc_symbol, color=hgnc_symbol)) +
	gghighlight(hgnc_symbol == "TLK1" |
							hgnc_symbol == "POMK", use_direct_label = FALSE) +
	geom_point(data = cluster_treatment_summary %>% filter(cluster_num == 8),
						 aes(x=treatment,y=mean_log2), color='blue',alpha=0.5) +
	geom_point(data = treatment_summary,
						 aes(x=treatment,y=mean_log2), color='red',alpha=0.5) +
	theme(axis.text.x=element_text(angle = -90, hjust = 0,vjust=0.5)) +
	xlab('') +
	ylab('Log 2 Fold Expression Change') +
	scale_color_discrete(name="Gene") +
	# facet_wrap(~hgnc_symbol) +
	theme_berginski()

ggsave(here('figures/clustering/kinase_cluster_8.png'))

kinase_DESeq_ratios_clusters %>% 
	filter(cluster_num == 8) %>% 
	group_by(hgnc_symbol,class) %>% 
	summarise(mean_log2 = mean(log2FoldChange, na.rm=T)) %>%
	arrange(desc(mean_log2)) %>%
	select(hgnc_symbol,mean_log2,class) %>%
	write_csv(here('cluster_sets/kinase_cluster_08.csv'))
```